base-files: Additional checks when trying to resize overlay
Signed-off-by: Anton Kikin <a.kikin@tano-systems.com>

diff --git a/meta-tanowrt/recipes-core/base-files/base-files/files/preinit/51_overlay_resize b/meta-tanowrt/recipes-core/base-files/base-files/files/preinit/51_overlay_resize
--- a/meta-tanowrt/recipes-core/base-files/base-files/files/preinit/51_overlay_resize
+++ b/meta-tanowrt/recipes-core/base-files/base-files/files/preinit/51_overlay_resize
@@ -67,6 +67,12 @@ do_overlay_resize() {
 
 	local ROOT_DEVICE=""
 	export_bootdevice
+
+	if [ "$?" != "0" ]; then
+		echo "overlay-resize: Cannot find boot device" > /dev/kmsg
+		return
+	fi
+
 	export_partdevice ROOT_DEVICE 0
 
 	if [ "${ROOT_DEVICE}" = "" ]; then
